# Tomcat
server:
  port: 9090

# Spring
spring:
  application:
    # 应用名称
    name: eureka-demo

# Eureka
eureka:
  server:
    # default is true
    enable-self-preservation: true
    # default is 0.85 we can set the value to 0.49
    renewalPercentThreshold: 0.49
  instance:
    # default is 30
    leaseRenewalIntervalInSeconds: 30
  client:
    sevice-url:
      defaultZone: http://127.0.0.1:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
